config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'images#index', as: "images" # main page
  get '/secretnsfwpage', to: "images#index_nsfw" # nsfw main page
  get '/images/:id', to: "images#show_router", as: "image"
  get '/new', to: "images#new", as: "new_image"

  get '/.well-known/pki-validation/E8DB7BA1796C667107D79492B04DF9FA.txt', to: "images#ssl" # ssl validation
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  def self.get_previous_image(current_image)
    Image.where("images.id < ? ", current_image.id).order('created_at asc').last
  end
  def self.get_next_image(current_image)
    Image.where("images.id > ? ", current_image.id).order('created_at asc').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_admin!, only: :new

  def index
    @images = Image.where(nsfw: false).order(id: :asc)
    @footer = true;
  end

  def index_nsfw
    @images = Image.where(nsfw: true).order(id: :asc)
  end

  def show
    @footer = true;
  end

  def show_nsfw
  end

  def new
    @image = Image.new
  end

  def show_router
    @image = Image.find(params[:id])
    puts @image.nsfw
    if @image.nsfw
      render :action => "show_nsfw"
    else
      render :action => "show"
    end
  end

  def ssl
    render file: "#{Rails.root}/app/assets/files/E8DB7BA1796C667107D79492B04DF9FA.txt"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/index.html.erb
<% content_for :title, "The Garfield Cursed Image Gallery" %>

<center>
  <h2>Welcome to the</h2>
  <h1>Garfield Cursed Image Gallery!</h1>
</center>

<br>
<blockquote>
  <!--funny orang cat-->
  Over the past few months, I've been collecting so-called "cursed images" of Garfield, everyone's favorite Monday-hating
  comic strip cat. These are images that may be somewhat disturbing or otherworldly, or just plain strange. If you have a good image that you think should be on the site, or if you have a suggestion for the appearance of the site, send me an email at <a href="mailto:info@garfieldcursedimage.org">info@garfieldcursedimage.org</a>.
  Otherwise, I usually find new images to add pretty often. Anyway, enjoy the nightmare fuel!
</blockquote>
<br>

<blockquote>
  <center>
  <h2>Featured: Stay Safe</h2>
  <%= image_tag("featured/stay_safe.jpg", style: "max-width: 100%; width: 500px;", title: "garf wearing mask") %>
  </center>
</blockquote><br>

<hr><br>
<!-- IMAGES -->
<center>
<% @images.each do |f| %>
  <%= link_to image_tag(f.path, size: "300x300", title: f.name, :class => "garf"), image_path(f.id) %>
<% end %>
</center>

<br><hr><br>
<blockquote>
  <b><i>FULL DISCLAIMER:</i></b> I am not gaining any money whatsoever from this site, or from the images on this site.
  If you see an image here that you created, that's great! But please keep in mind that this site was created only for fun,
  as a side project to work on in my spare time. I find these images mostly on online browsing sites, or a friend sends
  them to me. I do not intend to have any monetary gain from it. Thank you.
</blockquote>
<br>

app/views/images/index_nsfw.html.erb
<body id="nsfw">
<% content_for :title, "The Garfield Cursed Image Gallery | NSFW" %>

<button id="back" onclick="window.location = '/'">Back to sanity</button>

<center>
  <h2>Welcome to the</h2>
  <h1>Garfield Cursed Image Gallery!</h1>
</center>

<br>
<blockquote>
  funny nsfw cat
  <!--Over the past few months, I've been collecting so-called "cursed images" of Garfield, everyone's favorite Monday-hating
  comic strip cat. These are images that may be somewhat disturbing or otherworldly, or just plain strange. If you have a good image that you think should be on the site, or if you have a suggestion for the appearance of the site, send me an email at <a href="mailto:info@garfieldcursedimage.org">info@garfieldcursedimage.org</a>.
  Otherwise, I usually find new images to add pretty often. Anyway, enjoy the nightmare fuel!-->
</blockquote>
<br>
<!-- IMAGES -->
<center>
<% @images.each do |f| %>
  <%= link_to image_tag(f.path, size: "300x300", title: f.name, :class => "garf"), image_path(f.id) %>
<% end %>
</center>
</body>

app/views/images/new.html.erb
if you're reading this then you are signed in (hopefully)<br>
signed in with email <%= current_admin.email %><br><br>
<%= link_to "Sign out", destroy_admin_session_path, method: :delete %>

app/views/images/show.html.erb
<% content_for :title, @image.name %>

<center><br>
  <%= link_to "≤", Image.where(nsfw: false).first, class: "nav_btn" %>
  <%= link_to "<", Image.where(nsfw: false).get_previous_image(@image), class: "nav_btn" %>
  <%= link_to "All", images_path, class: "nav_btn" %>
  <%= link_to ">", Image.where(nsfw: false).get_next_image(@image), class: "nav_btn" %>
  <%= link_to "≥", Image.where(nsfw: false).last, class: "nav_btn" %>

  <h1><%= @image.name %></h1>
  <!-- <h4>Added on <%= Date::MONTHNAMES[@image.created_at.month] %> <%= @image.created_at.day %>, <%= @image.created_at.year %></h4> -->
  <%= image_tag(@image.path, title: @image.name, class: 'garf_show') %>
</center>

app/views/images/show_nsfw.html.erb
<body id="nsfw">
<% content_for :title, @image.name %>

<center><br>
  <%= link_to "≤", Image.where(nsfw: true).first, class: "nav_btn" %>
  <%= link_to "<", Image.where(nsfw: true).get_previous_image(@image), class: "nav_btn" %>
  <%= link_to "All", "/secretnsfwpage", class: "nav_btn" %>
  <%= link_to ">", Image.where(nsfw: true).get_next_image(@image), class: "nav_btn" %>
  <%= link_to "≥", Image.where(nsfw: true).last, class: "nav_btn" %>

  <h1><%= @image.name %></h1>
  <%= image_tag(@image.path, title: @image.name, class: 'garf_show') %>
</center>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-148459062-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-148459062-1');
    </script>
  </head>

  <body>
    <%= yield %>
    <% if @footer %>
    <footer>
      <hr><p>
        v1.1 &#8226;
        <a href="https://github.com/camzillajs101/garfield-cursed-image" target="_blank" class="a_icon">
          <%= image_tag('other/github.png', class: "icon") %></a>&nbsp;
        <a href="mailto:info@garfieldcursedimage.org" class="a_icon">
          <%= image_tag('other/email.png', class: "icon") %></a>  &#8226;
        This site was created with Ruby on Rails. I'm kinda proud of it.
      </p>
    </footer>
    <% end %>
  </body>
</html>